RazorShop/Models/DTO.cs
using ModelLibrary;
using ModelLibrary.Categories;

namespace RazorShop.Models;

public class DTO
{
    public ICategory Category { get; set; }
    public  List<Product> Products { get; set; }
}

RazorShop/Models/ErrorViewModel.cs
namespace RazorShop.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

RazorShop/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelLibrary;
using ModelLibrary.CatalogsWarehouse;
using ModelLibrary.Categories;
using RazorShop.Models;

namespace RazorShop.Controllers;

public class CatalogController : Controller
{
    private IRepositiry categories;

    public CatalogController(IRepositiry _categories)
    {
        categories = _categories;
    }
    
    // GET
    public IActionResult GetProducts()
    {
        List<Product> products = new List<Product>();
        
        foreach (var item in categories.GetAllCategories())
            foreach (var product in item.GetProducts(Request.Headers["User-Agent"].ToString(), DateTime.Now))
                products.Add(product);
        
        return View(products);
    }

    public IActionResult GetCategories()
    {
        List<DTO> dataTransferObjects = new List<DTO>();

        foreach (var item in categories.GetAllCategories())
        {
            dataTransferObjects.Add(new DTO()
            {
                Category = item, 
                Products = item.GetProducts(Request.Headers["User-Agent"].ToString(), DateTime.Now)
            });
        }

        return View(dataTransferObjects);
    }
    
    [HttpGet]                       
    public IActionResult CreateProduct()
    {
        return View(categories.GetAllCategories());               
    }     
    
    [HttpPost]
    public IActionResult CreateProduct(string Title, decimal? Price,  string Category)
    {
        if (string.IsNullOrEmpty(Title) || Price is null || string.IsNullOrEmpty(Category))
            return LocalRedirect("~/Catalog/ErrorPage");
        
        categories.GetAllCategories().Where(i => i.Name == Category).FirstOrDefault().AddProduct(new Product(Title, Price.Value));
        return LocalRedirect("~/Catalog/GetProducts");               
    }  
    
    public IActionResult ErrorPage()
    {              
        return View();               
    }

    [HttpGet]
    public IActionResult CreateCategory()
    {
        return View();
    }

    [HttpPost]
    public IActionResult CreateCategory(int? Id, string? Title)
    {
        if (Id is null || string.IsNullOrEmpty(Title))
            return BadRequest();
        
        ICategory newCategory = new Category(Id.Value, Title);
        categories.AddCategory(newCategory);
        return LocalRedirect("~/Catalog/GetCategories");
    }

    public IActionResult GetInformationSelectedProduct(string productName)
    {
        Product findedProduct = null;
        
        foreach (var category in categories.GetAllCategories())
        {
            foreach (var product in category.GetProducts(Request.Headers["User-Agent"].ToString(), DateTime.Now))
            {
                if (product.Title == productName)
                {
                    findedProduct = product;
                    break;
                }
                    
            }
        }
        
        return View(findedProduct);
    }

}

RazorShop/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RazorShop.Models;

namespace RazorShop.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

RazorShop/Controllers/TimeController.cs
using Microsoft.AspNetCore.Mvc;
using ModelLibrary.Time;

namespace RazorShop.Controllers;

public class TimeController : Controller
{
    private IClock UtcCurrentClock { get; }
    public TimeController(IClock clock)
    {
        UtcCurrentClock = clock;
    }
    // GET
    public IActionResult Index()
    {
        //time.GetTime();
        return View(UtcCurrentClock);
    }
}

RazorShop/Views/Catalog/AddProduct.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add Product</h2>

<form method="post">
    <p>
        <label>Title</label><br/>
        <input type="text" name="Title"/>    
    </p>
    
    <p>
        <label>Price</label><br/>
        <input type="number" name="Price"/>
    </p>
    
    <p>
        <label>Category</label><br/>
        <input type="text" name="Category"/>
    </p>
    
    <p>
        <input type="submit" value="Send"/>
    </p>
</form>

RazorShop/Views/Catalog/CreateCategory.cshtml
@model dynamic

@{
    ViewBag.Title = "Create category";
    Layout = "_Layout";
}

<h2>Create new category</h2>

<form method="post">
    <p>
        <label>Id</label><br/>
        <input type="number" name="Id"/>    
    </p>
    
    <p>
        <label>Title</label><br/>
        <input type="text" name="Title"/>
    </p>
    
    <p>
        <input type="submit" value="Create"/>
    </p>
</form>

RazorShop/Views/Catalog/CreateProduct.cshtml
@using ModelLibrary
@model List<ModelLibrary.Categories.ICategory>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add Product</h2>

<form method="post">
    <p>
        <label>Title</label><br/>
        <input type="text" name="Title"/>    
    </p>
    
    <p>
        <label>Price</label><br/>
        <input type="number" name="Price"/>
    </p>
    
    <p>
        <label>Category</label><br/>
        <select name="Category">
            @foreach (var item in Model)
            {
                <option value="@item.Name">@item.Name</option>
            }
        </select>
    </p>
    
    <p>
        <input type="submit" value="Send"/>
    </p>
</form>

RazorShop/Views/Catalog/ErrorPage.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Error Page</h2>
<h3>Error: Somethink parametrs is empty.</h3>

RazorShop/Views/Catalog/GetCategories.cshtml
@* @model List<ModelLibrary.ICatalog> *@
@model List<DTO>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


<h2>Categories</h2>
<ul>
    @foreach (var item in Model)
    {
        <li><b>Title category:</b> @item.Category.Name <b>Id:</b> @item.Category.Id</li>
    }
</ul>

<br/>
<br/>
<br/>

<h2>Products by categories</h2>
<select>
    @foreach (var category in Model)
    {
        <optgroup label="@category.Category.Name">
            @foreach (var itemProduct in category.Products)
            {
                <option>@itemProduct.Title Price - @itemProduct.Price</option>
            }
        </optgroup>
    }
</select>

RazorShop/Views/Catalog/GetInformationSelectedProduct.cshtml
@model ModelLibrary.Product

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


<h2>@Model.Title</h2>
<h2>@Model.Price</h2>

<div>
    Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.
    Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
    В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов,
    используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков,
    но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и,
    в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.
</div>

RazorShop/Views/Catalog/GetProducts.cshtml
@model List<ModelLibrary.Product>

@{
    ViewBag.Title = "List all products";
    Layout = "_Layout";
}

<h2>List all products</h2>
<ul>
    @foreach (var item in Model)
        {
            <li>@Html.ActionLink(@item.Title, "GetInformationSelectedProduct", new {productName=item.Title}) </li>
        }
    @* @foreach (var item in Model) *@
    @* { *@
    @*     <li>@item </li> *@
    @* } *@
</ul>

RazorShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RazorShop.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RazorShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="GetProducts">All Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="GetCategories">All Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="CreateProduct">Create Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="CreateCategory">Create category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Time" asp-action="Index">UTC Time</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - RazorShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RazorShop/Views/Time/Index.cshtml
@model ModelLibrary.Time.IClock

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Current time by UTC</h2>
<h3>@Model.GetTime()</h3>